package com.schoolexam.view;

import com.schoolexam.model.User;

public class DashboardView {

    public static String render(User user) {
        String teacherName = user != null && user.getFullName() != null ? user.getFullName() : "Prof. Sarah Jenkins";
        StringBuilder sb = new StringBuilder();
        sb.append("<!DOCTYPE html>\n");
        sb.append("<html lang=\"en\">\n");
        sb.append("<head>\n");
        sb.append("  <meta charset=\"UTF-8\">\n");
        sb.append("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        sb.append("  <title>GradePulse AI - Pure Java Exam Correction Hub</title>\n");
        sb.append("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
        sb.append("  <link rel=\"stylesheet\" href=\"/static/css/styles.css\">\n");
        sb.append("</head>\n");
        sb.append("<body>\n");
        sb.append("  <header class=\"glass-panel navbar\">\n");
        sb.append("    <a href=\"#\" class=\"brand\">\n");
        sb.append("      <div class=\"brand-logo\"><i class=\"fa-solid fa-graduation-cap\"></i></div>\n");
        sb.append("      <div class=\"brand-text\">\n");
        sb.append("        <h1>GradePulse AI</h1>\n");
        sb.append("        <span>Pure Java Exam Correction Engine</span>\n");
        sb.append("      </div>\n");
        sb.append("    </a>\n");
        sb.append("    <div class=\"nav-actions\">\n");
        sb.append("      <div class=\"user-badge\">\n");
        sb.append("        <div class=\"avatar\">TJ</div>\n");
        sb.append("        <div>\n");
        sb.append("          <strong style=\"display:block; font-size:0.88rem; color:#fff;\">").append(teacherName).append("</strong>\n");
        sb.append("          <span style=\"font-size:0.75rem; color:var(--text-muted);\">Lead Evaluator</span>\n");
        sb.append("        </div>\n");
        sb.append("      </div>\n");
        sb.append("      <a href=\"/logout\" class=\"btn btn-sm btn-secondary\"><i class=\"fa-solid fa-arrow-right-from-bracket\"></i> Sign Out</a>\n");
        sb.append("    </div>\n");
        sb.append("  </header>\n");
        sb.append("  <div class=\"container\">\n");
        sb.append("    <div class=\"grid-main\">\n");
        sb.append("      <aside class=\"sidebar\">\n");
        sb.append("        <div class=\"glass-panel control-card\">\n");
        sb.append("          <h3><i class=\"fa-solid fa-book-bookmark\" style=\"color:var(--primary-indigo);\"></i> Selected Exam</h3>\n");
        sb.append("          <div class=\"form-group\">\n");
        sb.append("            <label>Active Assessment</label>\n");
        sb.append("            <select id=\"examSelect\" class=\"form-select\"></select>\n");
        sb.append("          </div>\n");
        sb.append("          <button class=\"btn btn-sm btn-outline\" style=\"width:100%;\" onclick=\"exportCsv()\"><i class=\"fa-solid fa-file-csv\"></i> Download CSV Gradebook</button>\n");
        sb.append("        </div>\n");
        sb.append("        <div class=\"glass-panel control-card\">\n");
        sb.append("          <h3><i class=\"fa-solid fa-robot\" style=\"color:#34d399;\"></i> LLM Evaluation Model</h3>\n");
        sb.append("          <div class=\"form-group\">\n");
        sb.append("            <label>Active Free-Tier Model</label>\n");
        sb.append("            <select id=\"llmProviderSelect\" class=\"form-select\"></select>\n");
        sb.append("          </div>\n");
        sb.append("          <button class=\"btn btn-sm btn-secondary\" style=\"width:100%;\" onclick=\"openKeyModal()\"><i class=\"fa-solid fa-key\"></i> Configure API Key</button>\n");
        sb.append("        </div>\n");
        sb.append("      </aside>\n");
        sb.append("      <main>\n");
        sb.append("        <div class=\"glass-panel\" style=\"padding:1.75rem;\">\n");
        sb.append("          <div class=\"tabs-header\">\n");
        sb.append("            <button class=\"tab-btn active\" onclick=\"switchTab('single')\"><i class=\"fa-solid fa-file-arrow-up\"></i> Single Paper Correction</button>\n");
        sb.append("            <button class=\"tab-btn\" onclick=\"switchTab('bulk')\"><i class=\"fa-solid fa-folder-tree\"></i> Bulk Upload Scanner</button>\n");
        sb.append("            <button class=\"tab-btn\" onclick=\"switchTab('history')\"><i class=\"fa-solid fa-list-check\"></i> Submissions Gradebook</button>\n");
        sb.append("          </div>\n");
        sb.append("          <div id=\"tabSingle\" class=\"tab-content\">\n");
        sb.append("            <form id=\"singleUploadForm\">\n");
        sb.append("              <div class=\"dropzone\" onclick=\"document.getElementById('paperFileInput').click()\">\n");
        sb.append("                <div class=\"dropzone-icon\"><i class=\"fa-solid fa-cloud-arrow-up\"></i></div>\n");
        sb.append("                <h4>Drop Student Answer Sheet (PDF or Image)</h4>\n");
        sb.append("                <p>Supports scanned PDFs, PNG, JPG, WEBP. OCR Vision parsing enabled.</p>\n");
        sb.append("                <input type=\"file\" id=\"paperFileInput\" name=\"paperFile\" accept=\".pdf,.png,.jpg,.jpeg,.webp\" style=\"display:none;\" onchange=\"updateFileName(this)\">\n");
        sb.append("                <div id=\"selectedFileName\" style=\"margin-top:0.75rem; font-weight:600; color:var(--primary-indigo);\"></div>\n");
        sb.append("              </div>\n");
        sb.append("              <div style=\"display:grid; grid-template-columns: 1fr 1fr; gap:1rem; margin-top:1.25rem;\">\n");
        sb.append("                <div class=\"form-group\">\n");
        sb.append("                  <label>Student Roll Number (Optional)</label>\n");
        sb.append("                  <input type=\"text\" name=\"studentRollNumber\" class=\"form-input\" placeholder=\"Auto-detected if left empty\">\n");
        sb.append("                </div>\n");
        sb.append("                <div class=\"form-group\">\n");
        sb.append("                  <label>Student Name (Optional)</label>\n");
        sb.append("                  <input type=\"text\" name=\"studentName\" class=\"form-input\" placeholder=\"Auto-detected if left empty\">\n");
        sb.append("                </div>\n");
        sb.append("              </div>\n");
        sb.append("              <button type=\"submit\" class=\"btn btn-primary\" style=\"width:100%; margin-top:0.75rem;\"><i class=\"fa-solid fa-wand-magic-sparkles\"></i> Process OCR & Evaluate Paper</button>\n");
        sb.append("            </form>\n");
        sb.append("            <div id=\"scorecardDisplay\" class=\"glass-panel\" style=\"margin-top:2rem; overflow:hidden;\">\n");
        sb.append("              <div style=\"padding:3rem; text-align:center; color:var(--text-muted);\">\n");
        sb.append("                <i class=\"fa-solid fa-clipboard-check\" style=\"font-size:3rem; color:var(--border-glass); margin-bottom:1rem; display:block;\"></i>\n");
        sb.append("                Upload an answer sheet paper to view instant AI grading and feedback.\n");
        sb.append("              </div>\n");
        sb.append("            </div>\n");
        sb.append("          </div>\n");
        sb.append("          <div id=\"tabBulk\" class=\"tab-content\" style=\"display:none;\">\n");
        sb.append("            <form id=\"bulkUploadForm\">\n");
        sb.append("              <div class=\"dropzone\" onclick=\"document.getElementById('bulkFileInput').click()\">\n");
        sb.append("                <div class=\"dropzone-icon\"><i class=\"fa-solid fa-file-zipper\"></i></div>\n");
        sb.append("                <h4>Drop Bulk ZIP Archive of Student Papers</h4>\n");
        sb.append("                <p>Upload a .zip folder containing multiple PDF/image answer papers.</p>\n");
        sb.append("                <input type=\"file\" id=\"bulkFileInput\" name=\"bulkFile\" accept=\".zip\" style=\"display:none;\" onchange=\"updateBulkFileName(this)\">\n");
        sb.append("                <div id=\"selectedBulkFileName\" style=\"margin-top:0.75rem; font-weight:600; color:#34d399;\"></div>\n");
        sb.append("              </div>\n");
        sb.append("              <button type=\"submit\" class=\"btn btn-primary\" style=\"width:100%; margin-top:1.5rem;\"><i class=\"fa-solid fa-layer-group\"></i> Run Batch Bulk Correction</button>\n");
        sb.append("            </form>\n");
        sb.append("          </div>\n");
        sb.append("          <div id=\"tabHistory\" class=\"tab-content\" style=\"display:none;\">\n");
        sb.append("            <h3 style=\"font-family:var(--font-heading); margin-bottom:1rem;\">Evaluated Submissions</h3>\n");
        sb.append("            <div id=\"submissionsList\"></div>\n");
        sb.append("          </div>\n");
        sb.append("        </div>\n");
        sb.append("      </main>\n");
        sb.append("    </div>\n");
        sb.append("  </div>\n");
        sb.append("  <div id=\"overrideModal\" class=\"modal-overlay\">\n");
        sb.append("    <div class=\"glass-panel modal-content\">\n");
        sb.append("      <h3 style=\"font-family:var(--font-heading); margin-bottom:1rem; color:#fff;\">Override Marks & Evaluation</h3>\n");
        sb.append("      <input type=\"hidden\" id=\"overrideSubId\">\n");
        sb.append("      <div class=\"form-group\">\n");
        sb.append("        <label>New Total Marks Obtained</label>\n");
        sb.append("        <input type=\"number\" step=\"0.5\" id=\"overrideScoreInput\" class=\"form-input\">\n");
        sb.append("      </div>\n");
        sb.append("      <div class=\"form-group\">\n");
        sb.append("        <label>Teacher Override Justification Notes</label>\n");
        sb.append("        <textarea id=\"overrideNotesInput\" class=\"form-input\" rows=\"3\" placeholder=\"Explain score adjustment justification...\"></textarea>\n");
        sb.append("      </div>\n");
        sb.append("      <div style=\"display:flex; justify-content:flex-end; gap:1rem; margin-top:1.5rem;\">\n");
        sb.append("        <button class=\"btn btn-secondary\" onclick=\"closeCloseModal('overrideModal')\">Cancel</button>\n");
        sb.append("        <button class=\"btn btn-primary\" onclick=\"submitOverride()\">Save Override</button>\n");
        sb.append("      </div>\n");
        sb.append("    </div>\n");
        sb.append("  </div>\n");
        sb.append("  <div id=\"keyModal\" class=\"modal-overlay\">\n");
        sb.append("    <div class=\"glass-panel modal-content\">\n");
        sb.append("      <h3 style=\"font-family:var(--font-heading); margin-bottom:1rem; color:#fff;\">Configure Model API Key</h3>\n");
        sb.append("      <div class=\"form-group\">\n");
        sb.append("        <label>API Key for selected model</label>\n");
        sb.append("        <input type=\"password\" id=\"modalApiKeyInput\" class=\"form-input\" placeholder=\"Paste your API key here...\">\n");
        sb.append("      </div>\n");
        sb.append("      <div style=\"display:flex; justify-content:flex-end; gap:1rem; margin-top:1.5rem;\">\n");
        sb.append("        <button class=\"btn btn-secondary\" onclick=\"closeCloseModal('keyModal')\">Cancel</button>\n");
        sb.append("        <button class=\"btn btn-primary\" onclick=\"saveApiKey()\">Save API Key</button>\n");
        sb.append("      </div>\n");
        sb.append("    </div>\n");
        sb.append("  </div>\n");
        sb.append("  <div id=\"loadingOverlay\" class=\"modal-overlay\">\n");
        sb.append("    <div style=\"text-align:center;\">\n");
        sb.append("      <div class=\"spinner\"></div>\n");
        sb.append("      <p style=\"margin-top:1rem; font-weight:600; color:#fff;\">Running OCR & LLM Paper Correction...</p>\n");
        sb.append("    </div>\n");
        sb.append("  </div>\n");
        sb.append("  <script src=\"/static/js/app.js\"></script>\n");
        sb.append("  <script>\n");
        sb.append("    function switchTab(tab) {\n");
        sb.append("      document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));\n");
        sb.append("      document.querySelectorAll('.tab-content').forEach(c => c.style.display = 'none');\n");
        sb.append("      if (tab === 'single') {\n");
        sb.append("        document.getElementById('tabSingle').style.display = 'block';\n");
        sb.append("        event.target.classList.add('active');\n");
        sb.append("      } else if (tab === 'bulk') {\n");
        sb.append("        document.getElementById('tabBulk').style.display = 'block';\n");
        sb.append("        event.target.classList.add('active');\n");
        sb.append("      } else if (tab === 'history') {\n");
        sb.append("        document.getElementById('tabHistory').style.display = 'block';\n");
        sb.append("        event.target.classList.add('active');\n");
        sb.append("      }\n");
        sb.append("    }\n");
        sb.append("    function closeCloseModal(modalId) {\n");
        sb.append("      document.getElementById(modalId).style.display = 'none';\n");
        sb.append("    }\n");
        sb.append("    function updateFileName(input) {\n");
        sb.append("      if (input.files.length > 0) {\n");
        sb.append("        document.getElementById('selectedFileName').textContent = 'Selected: ' + input.files[0].name;\n");
        sb.append("      }\n");
        sb.append("    }\n");
        sb.append("    function updateBulkFileName(input) {\n");
        sb.append("      if (input.files.length > 0) {\n");
        sb.append("        document.getElementById('selectedBulkFileName').textContent = 'Selected: ' + input.files[0].name;\n");
        sb.append("      }\n");
        sb.append("    }\n");
        sb.append("  </script>\n");
        sb.append("</body>\n");
        sb.append("</html>\n");
        return sb.toString();
    }
}
