package com.schoolexam.view;

public class LoginView {

    public static String render(String contextPath, String errorMsg) {
        StringBuilder sb = new StringBuilder();
        sb.append("<!DOCTYPE html>\n");
        sb.append("<html lang=\"en\">\n");
        sb.append("<head>\n");
        sb.append("  <meta charset=\"UTF-8\">\n");
        sb.append("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        sb.append("  <title>GradePulse AI - Teacher Login (Pure Java UI)</title>\n");
        sb.append("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
        sb.append("  <style>\n");
        sb.append("    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700&family=Plus+Jakarta+Sans:wght@400;600&display=swap');\n");
        sb.append("    * { margin:0; padding:0; box-sizing:border-box; }\n");
        sb.append("    body { background: radial-gradient(circle at 15% 15%, #1e1b4b 0%, #0f172a 45%, #030712 100%); color:#f8fafc; font-family:'Plus Jakarta Sans', sans-serif; min-height:100vh; display:flex; align-items:center; justify-content:center; }\n");
        sb.append("    .glass-card { background: rgba(30, 41, 59, 0.75); backdrop-filter: blur(16px); border: 1px solid rgba(255,255,255,0.12); border-radius:24px; padding:2.5rem; width:100%; max-width:440px; box-shadow:0 8px 32px rgba(0,0,0,0.4); }\n");
        sb.append("    .brand-logo { width:56px; height:56px; background:linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%); border-radius:14px; display:flex; align-items:center; justify-content:center; font-size:1.8rem; color:#fff; margin:0 auto 1rem auto; box-shadow:0 0 25px rgba(99,102,241,0.4); }\n");
        sb.append("    h2 { font-family:'Outfit', sans-serif; font-size:1.75rem; text-align:center; color:#fff; }\n");
        sb.append("    p.sub { text-align:center; color:#94a3b8; font-size:0.9rem; margin-top:0.3rem; margin-bottom:1.75rem; }\n");
        sb.append("    .form-group { margin-bottom:1.25rem; }\n");
        sb.append("    label { display:block; font-size:0.82rem; font-weight:600; color:#94a3b8; text-transform:uppercase; margin-bottom:0.4rem; letter-spacing:0.5px; }\n");
        sb.append("    input { width:100%; padding:0.8rem 1rem; background:rgba(15,23,42,0.7); border:1px solid rgba(255,255,255,0.12); border-radius:8px; color:#fff; outline:none; font-size:0.95rem; }\n");
        sb.append("    input:focus { border-color:#6366f1; box-shadow:0 0 0 3px rgba(99,102,241,0.25); }\n");
        sb.append("    .btn { display:inline-flex; align-items:center; justify-content:center; gap:0.5rem; width:100%; padding:0.85rem; background:linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%); color:#fff; border:none; border-radius:12px; font-weight:600; font-size:0.95rem; cursor:pointer; margin-top:1rem; box-shadow:0 0 20px rgba(99,102,241,0.3); transition:all 0.2s; }\n");
        sb.append("    .btn:hover { transform:translateY(-2px); box-shadow:0 0 30px rgba(99,102,241,0.5); }\n");
        sb.append("    .alert { padding:0.75rem 1rem; background:rgba(244,63,94,0.2); border:1px solid #f43f5e; border-radius:8px; color:#fb7185; font-size:0.85rem; margin-bottom:1.5rem; display:").append(errorMsg != null ? "block" : "none").append("; }\n");
        sb.append("  </style>\n");
        sb.append("</head>\n");
        sb.append("<body>\n");
        sb.append("  <div class=\"glass-card\">\n");
        sb.append("    <div class=\"brand-logo\"><i class=\"fa-solid fa-graduation-cap\"></i></div>\n");
        sb.append("    <h2>GradePulse AI</h2>\n");
        sb.append("    <p class=\"sub\">Pure Java School Exam Correction Portal</p>\n");
        sb.append("    <div id=\"errorAlert\" class=\"alert\">").append(errorMsg != null ? errorMsg : "Invalid login credentials.").append("</div>\n");
        sb.append("    <form id=\"loginForm\">\n");
        sb.append("      <div class=\"form-group\">\n");
        sb.append("        <label>Teacher Email</label>\n");
        sb.append("        <input type=\"email\" id=\"emailInput\" value=\"teacher@school.edu\" required>\n");
        sb.append("      </div>\n");
        sb.append("      <div class=\"form-group\">\n");
        sb.append("        <label>Password</label>\n");
        sb.append("        <input type=\"password\" id=\"passwordInput\" value=\"teacher123\" required>\n");
        sb.append("      </div>\n");
        sb.append("      <button type=\"submit\" class=\"btn\"><i class=\"fa-solid fa-right-to-bracket\"></i> Sign In to Portal</button>\n");
        sb.append("    </form>\n");
        sb.append("    <div style=\"margin-top:1.75rem; padding-top:1.25rem; border-top:1px solid rgba(255,255,255,0.12); font-size:0.82rem; color:#94a3b8; text-align:center;\">\n");
        sb.append("      <strong>Demo Credentials:</strong><br>Email: <code style=\"color:#6366f1;\">teacher@school.edu</code> | Pass: <code style=\"color:#6366f1;\">teacher123</code>\n");
        sb.append("    </div>\n");
        sb.append("  </div>\n");
        sb.append("  <script>\n");
        sb.append("    document.getElementById('loginForm').addEventListener('submit', async (e) => {\n");
        sb.append("      e.preventDefault();\n");
        sb.append("      const email = document.getElementById('emailInput').value;\n");
        sb.append("      const password = document.getElementById('passwordInput').value;\n");
        sb.append("      const alertBox = document.getElementById('errorAlert');\n");
        sb.append("      try {\n");
        sb.append("        const res = await fetch('/login', {\n");
        sb.append("          method: 'POST',\n");
        sb.append("          headers: { 'Content-Type': 'application/json' },\n");
        sb.append("          body: JSON.stringify({ email, password })\n");
        sb.append("        });\n");
        sb.append("        if (res.ok) {\n");
        sb.append("          const data = await res.json();\n");
        sb.append("          window.location.href = data.redirect || '/dashboard';\n");
        sb.append("        } else {\n");
        sb.append("          alertBox.style.display = 'block';\n");
        sb.append("        }\n");
        sb.append("      } catch (err) {\n");
        sb.append("        alertBox.style.display = 'block';\n");
        sb.append("      }\n");
        sb.append("    });\n");
        sb.append("  </script>\n");
        sb.append("</body>\n");
        sb.append("</html>\n");
        return sb.toString();
    }
}
